version: "3"
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl.conf:/etc/nginx/ssl.conf
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 8443:8443
      - 443:443
  verify:
    image: nginx:latest
    volumes:
      - ./verify.nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443

